apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx1-cert
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  duration: 170000h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: "local.nginx"
  isCA: true
  dnsNames:
    - local.nginx
